### PR TITLE
Remove LabelList usage from the Java client

### PR DESCRIPTION
**Pull request by kaeaton**
Incorporates the changes to LabelData in the Swagger client.

### CODE REVIEW

**Comment by fscheel** [comment]
That looks far better! Now if we could avoid the tabs vs spaces debate...

**Comment by kaeaton** [comment]
I will fix that. Is it alright if I use depth of 4 spaces per tab instead of 8?

**Comment by fscheel** [comment]
I wouldn't mind a narrower indentation. Not sure if @mpresteg feels strongly about this.

**Comment by kaeaton** [comment]
It's currently set to tabs. The lines I changed Are currently set to 4 space tabs, but I double tabbed so that it still looks like 8. I also added a test data folder I need to the client. They're dummy data for testing the clients and have no impact on any of the code.

**Comment by mpresteg** [comment]
> I wouldn't mind a narrower indentation. Not sure if @mpresteg feels strongly about this.

Narrower is fine.  Any formatting preferences I may have established were not necessarily intentional.

**Comment by kaeaton** [comment]
Sorry to add one more commit to this, but I fixed the problem where swagger was rewriting the .gitignore file and generating junk files. It seemed important to add that as soon as possible.

**Comment by fscheel** [comment]
Sorry for having time to look at this only now, but why did you close this PR? Want me to separate your LabelList changes and get those merged in?

**Comment by kaeaton** [comment]
Can you sort out that last commit? (ec5333c) That one isn't ready yet. The rest is removing label list, adding some test files, and adding .gitignore to the correct .swagger-codegen-ignore and should all go in.

**Comment by fscheel** [comment]
I'm closing this in favour for #92

**Pull request closed without merging**
