### PR TITLE
Update the Java client to accommodate new LabelData structure

### PR DESCRIPTION
**Pull request by kaeaton**
LabelData and MethodData now directly include LabelList and MethodList. This update fixes the Java client so that it adds data to LabelData appropriately.

### CODE REVIEW

**Review by fscheel — COMMENTED** [review]
No time for a proper review considering the number of files in the PR, but one comment right away from me:

The paths were part of the `client/java/freq-client/.gitignore` by design because these files should get generated on every maven build. Could you undo the removal? The addition of autogenerated files creates a lot of noise here and will continue to do so in future PRs.

**Comment by kaeaton** [comment]
Terribly sorry, I must have accidentally deleted part of the file. (That's not the .gitignore I altered, and I returned that one to it's prior state.) The file has been repaired.

**Comment by fscheel** [comment]
Great! But sadly the now ignored files are still in the PR. Could you clean those up as well? https://stackoverflow.com/a/23839198 might help.

**Comment by kaeaton** [comment]
I made the changes, and just to check, recompiled the program. Something about compiling the program causes part of the .gitignore file to disappear which is how it picked up all those extra files. Do you have any ideas about what could cause that? I'm at a loss.

**Comment by fscheel** [comment]
That might be the swagger codegen also generating the `.gitignore` file... https://github.com/swagger-api/swagger-codegen/wiki/FAQ#how-to-skip-certain-files-during-code-generation might be a solution for that.

**Comment by kaeaton** [comment]
Let me submit a new pull request with the changes removing LabelList and I'll work on the .gitignore after.

**Pull request closed without merging**
